/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.test.java.los_piratas_do_futbol;

import app.src.main.java.los_piratas_do_futbol.LosPiratasDoFutbolWebApplication;

class AppTest {
    @Test void appHasAGreeting() {
        LosPiratasDoFutbolWebApplication classUnderTest = new LosPiratasDoFutbolWebApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String string) {
    }
}
