/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.main.java.fibra;

public class FibraWebApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            System.out.println(new FibraWebApplication().getGreeting());
            System.out.println("Ciao sono l'app della F.I.B.RA!! 🏴‍☠️");    
        } catch (Exception e) {
            System.err.println(e.getMessage() + e.getCause());
        }
    }
}