/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fibra;

class AppTest {
    @Test void appHasAGreeting() {
        FibraWebApplication classUnderTest = new FibraWebApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String string) {
    }
}
