/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.main.java.los_piratas_do_futbol;

public class LosPiratasDoFutbolWebApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            System.out.println(new LosPiratasDoFutbolWebApplication().getGreeting());
            System.out.println("Ciao sono l'app dei Los Piratas do Fùtbol!! 🏴‍☠️");    
        } catch (Exception e) {
            System.err.println(e.getMessage() + e.getCause());
        }
    }
}